[build]
  command = "bash scripts/deploy.sh"
  publish = "public/"

[[headers]]
  for = "/*"
  [headers.values]
  Cross-Origin-Opener-Policy = "same-origin"
  Cross-Origin-Embedder-Policy = "require-corp"
